//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 09:36:22 PM UTC 
//


package com.io7m.jdae.collada1_5.mathml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simple-size.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="simple-size"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="small"/&gt;
 *     &lt;enumeration value="normal"/&gt;
 *     &lt;enumeration value="big"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "simple-size")
@XmlEnum
public enum SimpleSize {

    @XmlEnumValue("small")
    SMALL("small"),
    @XmlEnumValue("normal")
    NORMAL("normal"),
    @XmlEnumValue("big")
    BIG("big");
    private final String value;

    SimpleSize(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SimpleSize fromValue(String v) {
        for (SimpleSize c: SimpleSize.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
