//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 09:36:22 PM UTC 
//


package com.io7m.jdae.collada1_5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fx_pipeline_stage_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="fx_pipeline_stage_enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="TESSELLATION"/&gt;
 *     &lt;enumeration value="VERTEX"/&gt;
 *     &lt;enumeration value="GEOMETRY"/&gt;
 *     &lt;enumeration value="FRAGMENT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "fx_pipeline_stage_enum")
@XmlEnum
public enum FxPipelineStageEnum {

    TESSELLATION,
    VERTEX,
    GEOMETRY,
    FRAGMENT;

    public String value() {
        return name();
    }

    public static FxPipelineStageEnum fromValue(String v) {
        return valueOf(v);
    }

}
