//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 09:36:22 PM UTC 
//


package com.io7m.jdae.collada1_5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gles_texenv_mode_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="gles_texenv_mode_enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="REPLACE"/&gt;
 *     &lt;enumeration value="MODULATE"/&gt;
 *     &lt;enumeration value="DECAL"/&gt;
 *     &lt;enumeration value="BLEND"/&gt;
 *     &lt;enumeration value="ADD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "gles_texenv_mode_enum")
@XmlEnum
public enum GlesTexenvModeEnum {

    REPLACE,
    MODULATE,
    DECAL,
    BLEND,
    ADD;

    public String value() {
        return name();
    }

    public static GlesTexenvModeEnum fromValue(String v) {
        return valueOf(v);
    }

}
