//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 09:36:22 PM UTC 
//


package com.io7m.jdae.collada1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for gles_texcombiner_argument_rgb_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gles_texcombiner_argument_rgb_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="source" type="{http://www.collada.org/2008/03/COLLADASchema}gles_texcombiner_source_enum" /&gt;
 *       &lt;attribute name="operand" type="{http://www.collada.org/2008/03/COLLADASchema}gles_texcombiner_operand_rgb_enum" default="SRC_COLOR" /&gt;
 *       &lt;attribute name="sampler" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gles_texcombiner_argument_rgb_type")
public class GlesTexcombinerArgumentRgbType {

    @XmlAttribute(name = "source")
    protected GlesTexcombinerSourceEnum source;
    @XmlAttribute(name = "operand")
    protected GlesTexcombinerOperandRgbEnum operand;
    @XmlAttribute(name = "sampler")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sampler;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link GlesTexcombinerSourceEnum }
     *     
     */
    public GlesTexcombinerSourceEnum getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlesTexcombinerSourceEnum }
     *     
     */
    public void setSource(GlesTexcombinerSourceEnum value) {
        this.source = value;
    }

    /**
     * Gets the value of the operand property.
     * 
     * @return
     *     possible object is
     *     {@link GlesTexcombinerOperandRgbEnum }
     *     
     */
    public GlesTexcombinerOperandRgbEnum getOperand() {
        if (operand == null) {
            return GlesTexcombinerOperandRgbEnum.SRC_COLOR;
        } else {
            return operand;
        }
    }

    /**
     * Sets the value of the operand property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlesTexcombinerOperandRgbEnum }
     *     
     */
    public void setOperand(GlesTexcombinerOperandRgbEnum value) {
        this.operand = value;
    }

    /**
     * Gets the value of the sampler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampler() {
        return sampler;
    }

    /**
     * Sets the value of the sampler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampler(String value) {
        this.sampler = value;
    }

}
