//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 09:36:22 PM UTC 
//


package com.io7m.jdae.collada1_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for gles_texenv_command_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gles_texenv_command_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="constant" type="{http://www.collada.org/2008/03/COLLADASchema}gles_texture_constant_type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="operator" type="{http://www.collada.org/2008/03/COLLADASchema}gles_texenv_mode_enum" /&gt;
 *       &lt;attribute name="sampler" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gles_texenv_command_type", propOrder = {
    "constant"
})
public class GlesTexenvCommandType {

    protected GlesTextureConstantType constant;
    @XmlAttribute(name = "operator")
    protected GlesTexenvModeEnum operator;
    @XmlAttribute(name = "sampler")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sampler;

    /**
     * Gets the value of the constant property.
     * 
     * @return
     *     possible object is
     *     {@link GlesTextureConstantType }
     *     
     */
    public GlesTextureConstantType getConstant() {
        return constant;
    }

    /**
     * Sets the value of the constant property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlesTextureConstantType }
     *     
     */
    public void setConstant(GlesTextureConstantType value) {
        this.constant = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link GlesTexenvModeEnum }
     *     
     */
    public GlesTexenvModeEnum getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlesTexenvModeEnum }
     *     
     */
    public void setOperator(GlesTexenvModeEnum value) {
        this.operator = value;
    }

    /**
     * Gets the value of the sampler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampler() {
        return sampler;
    }

    /**
     * Sets the value of the sampler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampler(String value) {
        this.sampler = value;
    }

}
