//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 09:36:22 PM UTC 
//


package com.io7m.jdae.collada1_5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * a program is one or more shaders linked together
 * 
 * <p>Java class for gles2_program_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gles2_program_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="shader" type="{http://www.collada.org/2008/03/COLLADASchema}gles2_shader_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="linker" type="{http://www.collada.org/2008/03/COLLADASchema}fx_target_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="bind_attribute" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="semantic" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute name="symbol" use="required" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="bind_uniform" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="param"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;group ref="{http://www.collada.org/2008/03/COLLADASchema}gles2_value_group"/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute name="symbol" use="required" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gles2_program_type", propOrder = {
    "shader",
    "linker",
    "bindAttribute",
    "bindUniform"
})
public class Gles2ProgramType {

    protected List<Gles2ShaderType> shader;
    protected List<FxTargetType> linker;
    @XmlElement(name = "bind_attribute")
    protected List<Gles2ProgramType.BindAttribute> bindAttribute;
    @XmlElement(name = "bind_uniform")
    protected List<Gles2ProgramType.BindUniform> bindUniform;

    /**
     * Gets the value of the shader property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a {@code set} method for the shader property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShader().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gles2ShaderType }
     * 
     * 
     */
    public List<Gles2ShaderType> getShader() {
        if (shader == null) {
            shader = new ArrayList<Gles2ShaderType>();
        }
        return this.shader;
    }

    /**
     * Gets the value of the linker property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a {@code set} method for the linker property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinker().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FxTargetType }
     * 
     * 
     */
    public List<FxTargetType> getLinker() {
        if (linker == null) {
            linker = new ArrayList<FxTargetType>();
        }
        return this.linker;
    }

    /**
     * Gets the value of the bindAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a {@code set} method for the bindAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBindAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gles2ProgramType.BindAttribute }
     * 
     * 
     */
    public List<Gles2ProgramType.BindAttribute> getBindAttribute() {
        if (bindAttribute == null) {
            bindAttribute = new ArrayList<Gles2ProgramType.BindAttribute>();
        }
        return this.bindAttribute;
    }

    /**
     * Gets the value of the bindUniform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a {@code set} method for the bindUniform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBindUniform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gles2ProgramType.BindUniform }
     * 
     * 
     */
    public List<Gles2ProgramType.BindUniform> getBindUniform() {
        if (bindUniform == null) {
            bindUniform = new ArrayList<Gles2ProgramType.BindUniform>();
        }
        return this.bindUniform;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="semantic" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
     *       &lt;/choice&gt;
     *       &lt;attribute name="symbol" use="required" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "semantic"
    })
    public static class BindAttribute {

        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String semantic;
        @XmlAttribute(name = "symbol", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String symbol;

        /**
         * Gets the value of the semantic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSemantic() {
            return semantic;
        }

        /**
         * Sets the value of the semantic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSemantic(String value) {
            this.semantic = value;
        }

        /**
         * Gets the value of the symbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSymbol() {
            return symbol;
        }

        /**
         * Sets the value of the symbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSymbol(String value) {
            this.symbol = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="param"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;group ref="{http://www.collada.org/2008/03/COLLADASchema}gles2_value_group"/&gt;
     *       &lt;/choice&gt;
     *       &lt;attribute name="symbol" use="required" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "param",
        "bool",
        "bvec2",
        "bvec3",
        "bvec4",
        "_float",
        "vec2",
        "vec3",
        "vec4",
        "mat2",
        "mat3",
        "mat4",
        "_int",
        "ivec2",
        "ivec3",
        "ivec4",
        "_enum",
        "sampler2D",
        "sampler3D",
        "samplerCUBE",
        "samplerDEPTH",
        "usertype",
        "array"
    })
    public static class BindUniform {

        protected Gles2ProgramType.BindUniform.Param param;
        protected Boolean bool;
        @XmlList
        @XmlElement(type = Boolean.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Boolean> bvec2;
        @XmlList
        @XmlElement(type = Boolean.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Boolean> bvec3;
        @XmlList
        @XmlElement(type = Boolean.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Boolean> bvec4;
        @XmlElement(name = "float")
        protected Double _float;
        @XmlList
        @XmlElement(type = Double.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Double> vec2;
        @XmlList
        @XmlElement(type = Double.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Double> vec3;
        @XmlList
        @XmlElement(type = Double.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Double> vec4;
        @XmlList
        @XmlElement(type = Double.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Double> mat2;
        @XmlList
        @XmlElement(type = Double.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Double> mat3;
        @XmlList
        @XmlElement(type = Double.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Double> mat4;
        @XmlElement(name = "int")
        protected Long _int;
        @XmlList
        @XmlElement(type = Long.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Long> ivec2;
        @XmlList
        @XmlElement(type = Long.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Long> ivec3;
        @XmlList
        @XmlElement(type = Long.class)
        @XmlSchemaType(name = "anySimpleType")
        protected List<Long> ivec4;
        @XmlElement(name = "enum")
        @XmlSchemaType(name = "anySimpleType")
        protected String _enum;
        protected FxSampler2DType sampler2D;
        protected FxSampler3DType sampler3D;
        protected FxSamplerCUBEType samplerCUBE;
        protected FxSamplerDEPTHType samplerDEPTH;
        protected com.io7m.jdae.collada1_5.Gles2NewparamType.Usertype usertype;
        protected com.io7m.jdae.collada1_5.Gles2NewparamType.Array array;
        @XmlAttribute(name = "symbol", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String symbol;

        /**
         * Gets the value of the param property.
         * 
         * @return
         *     possible object is
         *     {@link Gles2ProgramType.BindUniform.Param }
         *     
         */
        public Gles2ProgramType.BindUniform.Param getParam() {
            return param;
        }

        /**
         * Sets the value of the param property.
         * 
         * @param value
         *     allowed object is
         *     {@link Gles2ProgramType.BindUniform.Param }
         *     
         */
        public void setParam(Gles2ProgramType.BindUniform.Param value) {
            this.param = value;
        }

        /**
         * Gets the value of the bool property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isBool() {
            return bool;
        }

        /**
         * Sets the value of the bool property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setBool(Boolean value) {
            this.bool = value;
        }

        /**
         * Gets the value of the bvec2 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the bvec2 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBvec2().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Boolean }
         * 
         * 
         */
        public List<Boolean> getBvec2() {
            if (bvec2 == null) {
                bvec2 = new ArrayList<Boolean>();
            }
            return this.bvec2;
        }

        /**
         * Gets the value of the bvec3 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the bvec3 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBvec3().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Boolean }
         * 
         * 
         */
        public List<Boolean> getBvec3() {
            if (bvec3 == null) {
                bvec3 = new ArrayList<Boolean>();
            }
            return this.bvec3;
        }

        /**
         * Gets the value of the bvec4 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the bvec4 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBvec4().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Boolean }
         * 
         * 
         */
        public List<Boolean> getBvec4() {
            if (bvec4 == null) {
                bvec4 = new ArrayList<Boolean>();
            }
            return this.bvec4;
        }

        /**
         * Gets the value of the float property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getFloat() {
            return _float;
        }

        /**
         * Sets the value of the float property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setFloat(Double value) {
            this._float = value;
        }

        /**
         * Gets the value of the vec2 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the vec2 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVec2().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getVec2() {
            if (vec2 == null) {
                vec2 = new ArrayList<Double>();
            }
            return this.vec2;
        }

        /**
         * Gets the value of the vec3 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the vec3 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVec3().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getVec3() {
            if (vec3 == null) {
                vec3 = new ArrayList<Double>();
            }
            return this.vec3;
        }

        /**
         * Gets the value of the vec4 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the vec4 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVec4().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getVec4() {
            if (vec4 == null) {
                vec4 = new ArrayList<Double>();
            }
            return this.vec4;
        }

        /**
         * Gets the value of the mat2 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the mat2 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMat2().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getMat2() {
            if (mat2 == null) {
                mat2 = new ArrayList<Double>();
            }
            return this.mat2;
        }

        /**
         * Gets the value of the mat3 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the mat3 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMat3().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getMat3() {
            if (mat3 == null) {
                mat3 = new ArrayList<Double>();
            }
            return this.mat3;
        }

        /**
         * Gets the value of the mat4 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the mat4 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMat4().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getMat4() {
            if (mat4 == null) {
                mat4 = new ArrayList<Double>();
            }
            return this.mat4;
        }

        /**
         * Gets the value of the int property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getInt() {
            return _int;
        }

        /**
         * Sets the value of the int property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setInt(Long value) {
            this._int = value;
        }

        /**
         * Gets the value of the ivec2 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the ivec2 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIvec2().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public List<Long> getIvec2() {
            if (ivec2 == null) {
                ivec2 = new ArrayList<Long>();
            }
            return this.ivec2;
        }

        /**
         * Gets the value of the ivec3 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the ivec3 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIvec3().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public List<Long> getIvec3() {
            if (ivec3 == null) {
                ivec3 = new ArrayList<Long>();
            }
            return this.ivec3;
        }

        /**
         * Gets the value of the ivec4 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a {@code set} method for the ivec4 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIvec4().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public List<Long> getIvec4() {
            if (ivec4 == null) {
                ivec4 = new ArrayList<Long>();
            }
            return this.ivec4;
        }

        /**
         * Gets the value of the enum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnum() {
            return _enum;
        }

        /**
         * Sets the value of the enum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnum(String value) {
            this._enum = value;
        }

        /**
         * Gets the value of the sampler2D property.
         * 
         * @return
         *     possible object is
         *     {@link FxSampler2DType }
         *     
         */
        public FxSampler2DType getSampler2D() {
            return sampler2D;
        }

        /**
         * Sets the value of the sampler2D property.
         * 
         * @param value
         *     allowed object is
         *     {@link FxSampler2DType }
         *     
         */
        public void setSampler2D(FxSampler2DType value) {
            this.sampler2D = value;
        }

        /**
         * Gets the value of the sampler3D property.
         * 
         * @return
         *     possible object is
         *     {@link FxSampler3DType }
         *     
         */
        public FxSampler3DType getSampler3D() {
            return sampler3D;
        }

        /**
         * Sets the value of the sampler3D property.
         * 
         * @param value
         *     allowed object is
         *     {@link FxSampler3DType }
         *     
         */
        public void setSampler3D(FxSampler3DType value) {
            this.sampler3D = value;
        }

        /**
         * Gets the value of the samplerCUBE property.
         * 
         * @return
         *     possible object is
         *     {@link FxSamplerCUBEType }
         *     
         */
        public FxSamplerCUBEType getSamplerCUBE() {
            return samplerCUBE;
        }

        /**
         * Sets the value of the samplerCUBE property.
         * 
         * @param value
         *     allowed object is
         *     {@link FxSamplerCUBEType }
         *     
         */
        public void setSamplerCUBE(FxSamplerCUBEType value) {
            this.samplerCUBE = value;
        }

        /**
         * Gets the value of the samplerDEPTH property.
         * 
         * @return
         *     possible object is
         *     {@link FxSamplerDEPTHType }
         *     
         */
        public FxSamplerDEPTHType getSamplerDEPTH() {
            return samplerDEPTH;
        }

        /**
         * Sets the value of the samplerDEPTH property.
         * 
         * @param value
         *     allowed object is
         *     {@link FxSamplerDEPTHType }
         *     
         */
        public void setSamplerDEPTH(FxSamplerDEPTHType value) {
            this.samplerDEPTH = value;
        }

        /**
         * Gets the value of the usertype property.
         * 
         * @return
         *     possible object is
         *     {@link com.io7m.jdae.collada1_5.Gles2NewparamType.Usertype }
         *     
         */
        public com.io7m.jdae.collada1_5.Gles2NewparamType.Usertype getUsertype() {
            return usertype;
        }

        /**
         * Sets the value of the usertype property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.io7m.jdae.collada1_5.Gles2NewparamType.Usertype }
         *     
         */
        public void setUsertype(com.io7m.jdae.collada1_5.Gles2NewparamType.Usertype value) {
            this.usertype = value;
        }

        /**
         * Gets the value of the array property.
         * 
         * @return
         *     possible object is
         *     {@link com.io7m.jdae.collada1_5.Gles2NewparamType.Array }
         *     
         */
        public com.io7m.jdae.collada1_5.Gles2NewparamType.Array getArray() {
            return array;
        }

        /**
         * Sets the value of the array property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.io7m.jdae.collada1_5.Gles2NewparamType.Array }
         *     
         */
        public void setArray(com.io7m.jdae.collada1_5.Gles2NewparamType.Array value) {
            this.array = value;
        }

        /**
         * Gets the value of the symbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSymbol() {
            return symbol;
        }

        /**
         * Sets the value of the symbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSymbol(String value) {
            this.symbol = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Param {

            @XmlAttribute(name = "ref", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NCName")
            protected String ref;

            /**
             * Gets the value of the ref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRef(String value) {
                this.ref = value;
            }

        }

    }

}
