//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 09:32:10 PM UTC 
//


package com.io7m.jdae.collada1_4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Common_profile_input.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="Common_profile_input"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="BINORMAL"/&gt;
 *     &lt;enumeration value="COLOR"/&gt;
 *     &lt;enumeration value="CONTINUITY"/&gt;
 *     &lt;enumeration value="IMAGE"/&gt;
 *     &lt;enumeration value="IN_TANGENT"/&gt;
 *     &lt;enumeration value="INPUT"/&gt;
 *     &lt;enumeration value="INTERPOLATION"/&gt;
 *     &lt;enumeration value="INV_BIND_MATRIX"/&gt;
 *     &lt;enumeration value="JOINT"/&gt;
 *     &lt;enumeration value="LINEAR_STEPS"/&gt;
 *     &lt;enumeration value="MORPH_TARGET"/&gt;
 *     &lt;enumeration value="MORPH_WEIGHT"/&gt;
 *     &lt;enumeration value="NORMAL"/&gt;
 *     &lt;enumeration value="OUTPUT"/&gt;
 *     &lt;enumeration value="OUT_TANGENT"/&gt;
 *     &lt;enumeration value="POSITION"/&gt;
 *     &lt;enumeration value="TANGENT"/&gt;
 *     &lt;enumeration value="TEXBINORMAL"/&gt;
 *     &lt;enumeration value="TEXCOORD"/&gt;
 *     &lt;enumeration value="TEXTANGENT"/&gt;
 *     &lt;enumeration value="UV"/&gt;
 *     &lt;enumeration value="VERTEX"/&gt;
 *     &lt;enumeration value="WEIGHT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Common_profile_input")
@XmlEnum
public enum CommonProfileInput {

    BINORMAL,
    COLOR,
    CONTINUITY,
    IMAGE,
    IN_TANGENT,
    INPUT,
    INTERPOLATION,
    INV_BIND_MATRIX,
    JOINT,
    LINEAR_STEPS,
    MORPH_TARGET,
    MORPH_WEIGHT,
    NORMAL,
    OUTPUT,
    OUT_TANGENT,
    POSITION,
    TANGENT,
    TEXBINORMAL,
    TEXCOORD,
    TEXTANGENT,
    UV,
    VERTEX,
    WEIGHT;

    public String value() {
        return name();
    }

    public static CommonProfileInput fromValue(String v) {
        return valueOf(v);
    }

}
